openapi: 3.1.0
info:
  title: PREZAssistant Plugin
  version: 1.0.0
  description: Fournit les règles, templates et exemples de présentations HTML 16:9.
servers:
  - url: https://visitune.github.io/prezassistant
    description: GitHub Pages base URL for static JSON
paths:
  /data/instructions.json:
    get:
      operationId: getInstructions
      summary: Récupère les instructions de design PREZAssistant
      responses:
        '200':
          description: Données JSON de structure et contraintes
          content:
            application/json:
              schema:
                type: object

  /data/templates.json:
    get:
      operationId: getTemplates
      summary: Récupère les modèles de slides PREZAssistant
      responses:
        '200':
          description: Liste de templates de slides
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /data/examples.json:
    get:
      operationId: getExamples
      summary: Récupère des exemples complets de présentations
      responses:
        '200':
          description: Présentations HTML complètes (structurées)
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object


