openapi: 3.1.0
info:
  title: PREZAssistant Plugin
  version: 1.0.0
  description: Fournit les règles, templates et exemples de présentations HTML 16:9.
servers:
  - url: https://visitune.github.io/prezassistant
    description: GitHub Pages - base URL pour l’API statique
paths:
  /data/instructions.json:
    get:
      operationId: getInstructions
      summary: Récupère les instructions de design PREZAssistant
      responses:
        '200':
          description: Contraintes de design et de structure (JSON)
          content:
            application/json:
              schema:
                type: object

  /data/templates.json:
    get:
      operationId: getTemplates
      summary: Récupère les modèles de slides PREZAssistant
      responses:
        '200':
          description: Liste JSON de templates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /data/examples.json:
    get:
      operationId: getExamples
      summary: Récupère des exemples complets de présentations
      responses:
        '200':
          description: Présentations HTML complètes structurées
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

