openapi: 3.1.0
info:
  title: PREZAssistant Static Plugin
  version: 1.0.0
  description: Accès en lecture aux règles de structuration, design et exemples PREZAssistant via GitHub.
servers:
  - url: https://raw.githubusercontent.com/ton-org/prezassistant/main
paths:
  /data/instructions.json:
    get:
      operationId: getInstructions
      summary: Récupère les règles de design PREZAssistant
      responses:
        '200':
          description: Contenu brut des instructions PREZAssistant
          content:
            application/json:
              schema:
                type: object
  /data/templates.json:
    get:
      operationId: getTemplates
      summary: Récupère les templates de slides
      responses:
        '200':
          description: Exemples de slides structurés
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /data/examples.json:
    get:
      operationId: getExamples
      summary: Récupère des présentations complètes d'exemple
      responses:
        '200':
          description: Exemples complets de présentations HTML
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
