openapi: 3.1.0
info:
  title: PREZAssistant Plugin
  version: 1.0.0
  description: Fournit les règles, templates et exemples de présentations HTML 16:9 au format PowerPoint.
servers:
  - url: https://visitune.github.io/prezassistant
    description: GitHub Pages - PREZAssistant plugin base path
paths:
  /data/instructions.json:
    get:
      operationId: getInstructions
      summary: Règles de design PREZAssistant
      responses:
        '200':
          description: JSON des contraintes de structure et design
          content:
            application/json:
              schema:
                type: object

  /data/templates.json:
    get:
      operationId: getTemplates
      summary: Templates de slides standardisés
      responses:
        '200':
          description: Liste de templates de slides
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /data/examples.json:
    get:
      operationId: getExamples
      summary: Exemples complets de présentations
      responses:
        '200':
          description: Exemples complets de présentations générées
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

